<a href="https://colab.research.google.com/github/Ch-varshitha/Pandas/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

pandas is used for data manipulation,data cleaning,data changing,reading and writing data files
 and data analysis.data analysis refers to extracting meaningful data from the raw data.

In [13]:
import numpy as np
import pandas as pd


In [14]:
pd.DataFrame({
  "A":[10,20,30,40,50],
  "B":['a','b','c','d','e'],
  "C":np.random.randint(1,5)
})

,A,B,C
0,10,a,4
1,20,b,4
2,30,c,4
3,40,d,4
4,50,e,4


In [15]:
pd.DataFrame(
    np.random.randint(0,9,(10,4)),columns=["A","B","C","D"]
)

,A,B,C,D
0,5,1,4,6
1,2,1,8,3
2,8,4,2,7
3,6,7,7,7
4,0,4,3,1
5,6,8,2,6
6,1,0,6,7
7,5,4,4,4
8,5,6,1,7
9,4,8,8,1


In [16]:
np.random.rand(10,3).round(2)

array([[0.62, 0.85, 0.67],
       [0.88, 0.87, 0.28],
       [0.54, 0.1 , 0.69],
       [0.7 , 0.15, 0.01],
       [0.9 , 0.14, 0.21],
       [0.96, 0.42, 0.64],
       [0.1 , 0.41, 0.66],
       [0.89, 0.12, 0.51],
       [0.01, 0.75, 0.5 ],
       [0.22, 0.62, 0.  ]])

In [17]:
dfx=pd.DataFrame(
    np.random.randint(0,9,(10,4)),columns=["A","B","C","D"]
)

In [18]:
dfx.to_excel("abcd.xlsx")

In [19]:
pd.read_excel("abcd.xlsx")

,Unnamed: 0,A,B,C,D
0,0,6,0,8,7
1,1,2,4,7,3
2,2,5,8,2,4
3,3,8,6,6,4
4,4,8,4,3,0
5,5,4,2,1,4
6,6,7,7,8,1
7,7,5,7,2,6
8,8,5,2,2,1
9,9,8,7,4,1


In [20]:
df=pd.DataFrame(
    np.random.rand(10,3).round(2),columns=["AA","BB","CC"]
)

In [21]:
df.to_excel("varshi.xlsx")

In [22]:
pd.read_excel("varshi.xlsx")

,Unnamed: 0,AA,BB,CC
0,0,0.05,0.82,0.43
1,1,0.76,0.29,0.02
2,2,0.61,0.41,0.77
3,3,0.99,0.45,0.05
4,4,0.79,0.81,0.34
5,5,0.19,0.78,0.17
6,6,0.80,0.92,0.42
7,7,0.28,0.53,0.51
8,8,0.59,0.46,0.48
9,9,0.75,0.28,0.80


In [23]:
df['d']=np.random.randint(1,9)

In [24]:
df.describe(include="all")

,AA,BB,CC,d
count,10.000000,10.000000,10.000000,10.0
mean,0.581000,0.575000,0.399000,5.0
std,0.306574,0.236326,0.266685,0.0
min,0.050000,0.280000,0.020000,5.0
25%,0.357500,0.420000,0.212500,5.0
50%,0.680000,0.495000,0.425000,5.0
75%,0.782500,0.802500,0.502500,5.0
max,0.990000,0.920000,0.800000,5.0


In [25]:
 df.drop('AA',axis=1)

,BB,CC,d
0,0.82,0.43,5
1,0.29,0.02,5
2,0.41,0.77,5
3,0.45,0.05,5
4,0.81,0.34,5
5,0.78,0.17,5
6,0.92,0.42,5
7,0.53,0.51,5
8,0.46,0.48,5
9,0.28,0.80,5


In [26]:
df['AA']=df['CC'].apply(lambda x:'big' if x>0.5 else 'small')

In [27]:
df

,AA,BB,CC,d
0,small,0.82,0.43,5
1,small,0.29,0.02,5
2,big,0.41,0.77,5
3,small,0.45,0.05,5
4,small,0.81,0.34,5
5,small,0.78,0.17,5
6,small,0.92,0.42,5
7,big,0.53,0.51,5
8,small,0.46,0.48,5
9,big,0.28,0.80,5


In [28]:
df.to_excel("ch.xlsx")

In [29]:
df.drop(5)

,AA,BB,CC,d
0,small,0.82,0.43,5
1,small,0.29,0.02,5
2,big,0.41,0.77,5
3,small,0.45,0.05,5
4,small,0.81,0.34,5
6,small,0.92,0.42,5
7,big,0.53,0.51,5
8,small,0.46,0.48,5
9,big,0.28,0.80,5


In [30]:
np.arange(10,1001,10)

array([  10,   20,   30,   40,   50,   60,   70,   80,   90,  100,  110,
        120,  130,  140,  150,  160,  170,  180,  190,  200,  210,  220,
        230,  240,  250,  260,  270,  280,  290,  300,  310,  320,  330,
        340,  350,  360,  370,  380,  390,  400,  410,  420,  430,  440,
        450,  460,  470,  480,  490,  500,  510,  520,  530,  540,  550,
        560,  570,  580,  590,  600,  610,  620,  630,  640,  650,  660,
        670,  680,  690,  700,  710,  720,  730,  740,  750,  760,  770,
        780,  790,  800,  810,  820,  830,  840,  850,  860,  870,  880,
        890,  900,  910,  920,  930,  940,  950,  960,  970,  980,  990,
       1000])

In [31]:
df.set_index(np.arange(1,100,10))

,AA,BB,CC,d
1,small,0.82,0.43,5
11,small,0.29,0.02,5
21,big,0.41,0.77,5
31,small,0.45,0.05,5
41,small,0.81,0.34,5
51,small,0.78,0.17,5
61,small,0.92,0.42,5
71,big,0.53,0.51,5
81,small,0.46,0.48,5
91,big,0.28,0.80,5


In [32]:
df.loc[4,'BB']

np.float64(0.81)

In [34]:
df.iloc[2,2]


np.float64(0.77)

In [36]:
st="this is python"

In [39]:
st[2:12:3]

'iiph'

In [43]:
ar=np.random.randint(11,99,(4,5,6))

In [45]:
ar

array([[[27, 20, 83, 23, 54, 74],
        [20, 27, 49, 12, 60, 46],
        [14, 17, 95, 96, 11, 37],
        [81, 24, 78, 85, 61, 11],
        [58, 30, 61, 96, 11, 33]],

       [[57, 28, 12, 45, 82, 66],
        [90, 34, 37, 76, 37, 46],
        [96, 61, 47, 15, 93, 84],
        [29, 46, 77, 84, 98, 96],
        [42, 17, 60, 70, 62, 33]],

       [[49, 27, 20, 41, 61, 24],
        [49, 18, 78, 42, 51, 45],
        [91, 93, 27, 79, 70, 23],
        [94, 60, 93, 84, 92, 13],
        [21, 14, 52, 73, 71, 82]],

       [[61, 44, 48, 13, 66, 48],
        [39, 30, 81, 50, 19, 54],
        [17, 21, 80, 68, 23, 46],
        [87, 72, 40, 17, 21, 73],
        [30, 15, 93, 44, 72, 97]]])

In [47]:
ar[2,2,3]

np.int64(79)

In [49]:
ar[2,3,:]

array([94, 60, 93, 84, 92, 13])

In [51]:
ar[2,:,2]

array([20, 78, 27, 93, 52])

In [53]:
ar[2,:,:]

array([[49, 27, 20, 41, 61, 24],
       [49, 18, 78, 42, 51, 45],
       [91, 93, 27, 79, 70, 23],
       [94, 60, 93, 84, 92, 13],
       [21, 14, 52, 73, 71, 82]])

In [55]:
ar[:,3,:]

array([[81, 24, 78, 85, 61, 11],
       [29, 46, 77, 84, 98, 96],
       [94, 60, 93, 84, 92, 13],
       [87, 72, 40, 17, 21, 73]])

In [57]:
ar[:,:,2]

array([[83, 49, 95, 78, 61],
       [12, 37, 47, 77, 60],
       [20, 78, 27, 93, 52],
       [48, 81, 80, 40, 93]])

In [58]:
ar2=np.random.randint(11,12,9)


In [60]:
ar2

array([11, 11, 11, 11, 11, 11, 11, 11, 11])

In [62]:
newar=np.zeros((7,3,5,9))

In [64]:
newar.shape

(7, 3, 5, 9)

In [79]:
newar[2,1,2,3].shape

()

In [81]:
newar[2,1,2,2:6].shape

(4,)

In [83]:
newar[2:5,1:3,2:2,2:6].shape

(3, 2, 0, 4)

RANGE OF INDEX IN PANDAS


RANGE OF INDEX


In [86]:
ndf=pd.DataFrame({
    "first":np.random.randint(11,99,10),
    "second":np.random.randint(11,99,10),
    "third":np.random.randint(11,99,10)

})

In [88]:
ndf

,first,second,third
0,12,69,13
1,24,16,80
2,79,62,38
3,59,30,74
4,23,72,38
5,73,63,25
6,40,24,55
7,78,35,68
8,79,29,52
9,35,24,48


In [90]:
ndf.set_index(np.arange(10,20),inplace=True)

In [91]:
ndf.iloc[:,2]

,third
10,13
11,80
12,38
13,74
14,38
15,25
16,55
17,68
18,52
19,48


In [94]:
ndf.iloc[:,2]#all of the rows and restricted to second column


,third
10,13
11,80
12,38
13,74
14,38
15,25
16,55
17,68
18,52
19,48


In [98]:

ndf.iloc[6,:]#resrticted to sixth row but all of the columns



,16
first,40
second,24
third,55


In [100]:
ndf.iloc[3:8,2:4]

,third
13,74
14,38
15,25
16,55
17,68
